services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=catsgram
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

    # ещё один сервис
  db-init:
    image: postgres:16.1
    container_name: db-init
    # секция для указания зависимостей от других сервисов
    depends_on:
      # указываем, что этот сервис зависит от сервиса с именем db
      db:
        # указываем, что условием запуска будет момент, когда
        # сервис db будет в «здоровом» состоянии
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://dbuser:12345@db:5432/catsgram -v ON_ERROR_STOP=1 <<-EOSQL
          CREATE TABLE IF NOT EXISTS animal (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY,
              name varchar(40) NOT NULL,
              age integer NOT NULL,
              date_birthday date, 
              CONSTRAINT catsgram_pk PRIMARY KEY (id)              
          );
          INSERT INTO animal (name, age, date_birthday)
          VALUES 
              ('Mishon', 5, '2016-07-20'),
              ('Black', 6, '2017-03-10'),
              ('Kitti', 1, '2021-11-05');
        EOSQL